packages:
  - playground

catalogs:
  dev:
    '@antfu/eslint-config': ^4.11.0
    '@antfu/ni': ^24.3.0
    '@antfu/utils': ^9.2.0
    '@iconify/json': ^2.2.323
    '@types/codemirror': ^5.60.15
    '@types/debug': ^4.1.12
    '@types/node': ^22.14.0
    '@unocss/eslint-config': ^66.0.0
    '@unocss/eslint-plugin': ^66.0.0
    '@vitejs/plugin-vue': ^5.2.3
    '@vue/compiler-sfc': ^3.5.13
    bumpp: ^10.1.0
    eslint: ^9.23.0
    lint-staged: ^15.5.0
    rimraf: ^6.0.1
    serve: ^14.2.4
    simple-git-hooks: ^2.12.1
    typescript: ^5.8.2
    unbuild: ^3.5.0
    unocss: ^66.0.0
    unplugin-auto-import: ^19.1.2
    unplugin-vue-components: ^28.4.1
    unplugin-vue-router: ^0.12.0
    vite: npm:rolldown-vite@6.3.0-beta.5
    vue-tsc: ^2.2.8

  frontend:
    '@vueuse/core': ^13.0.0
    '@vueuse/router': ^13.0.0
    codemirror: ^5.65.16
    codemirror-theme-vars: ^0.1.2
    comlink: ^4.4.2
    diff-match-patch-es: ^1.0.1
    echarts: ^5.6.0
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    ohash: ^2.0.11
    pathe: ^2.0.3
    perfect-debounce: ^1.0.0
    pinia: ^3.0.1
    splitpanes: ^4.0.3
    vis-data: ^7.1.7
    vis-network: ^9.1.6
    vite-dev-rpc: ^1.0.7
    vite-hot-client: ^2.0.4
    vue: ^3.5.13
    vue-echarts: ^7.0.3
    vue-router: ^4.5.0

  prod:
    '@nuxt/kit': ^3.16.2
    ansis: ^3.17.0
    debug: ^4.4.0
    error-stack-parser-es: ^1.0.5
    open: ^10.1.0
    sirv: ^3.0.1
    unplugin-utils: ^0.2.4

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - vue-demi
